services:

  # message queue
  rabbitmq:
    image: rabbitmq:3-management
    container_name: microservices-rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq123
    networks:
      - microservices-network

  # Bases de datos
  postgres:
    image: postgres:15
    container_name: microservices-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  mongodb:
    image: mongo:7
    container_name: microservices-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
      MONGO_INITDB_DATABASE: productdb
    ports:
      - '28017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

  redis:
    image: redis:7-alpine
    container_name: microservices-redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - microservices-network

  # API Gateway
  api-gateway:
    build:
      context: ./ecommerce-api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - NOTIFICATION_SERVICE_URL=http://notification-service:3003
      - SHOPPING_CART_SERVICE_URL=http://shopping-cart-service:3006
      - ORDERS_SERVICE_URL=http://orders-service:3004
      - PAYMENTS_SERVICE_URL=http://payments-service:3005
      - RABBITMQ_URLS=amqp://rabbitmq:rabbitmq123@microservices-rabbitmq:5672,
      - RABBITMQ_QUEUE=ecommerce_queue
    depends_on:
      - user-service
      - product-service
      - notification-service
      - shopping-cart-service
      - orders-service
      - payments-service
    networks:
      - microservices-network
    volumes:
      - ./ecommerce-api-gateway/src:/usr/src/app/src
      - ./ecommerce-api-gateway/package.json:/usr/src/app/package.json
      - ./ecommerce-api-gateway/tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules

  # User Service
  user-service:
    build:
      context: ./ecommerce-users-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=userdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres123
      - JWT_SECRET=your-super-secret-jwt-key
      - RABBITMQ_URLS=amqp://rabbitmq:rabbitmq123@microservices-rabbitmq:5672,
      - RABBITMQ_QUEUE=ecommerce_queue
    depends_on:
      - postgres
    networks:
      - microservices-network
    volumes:
      - ./ecommerce-users-service/src:/usr/src/app/src
      - ./ecommerce-users-service/package.json:/usr/src/app/package.json
      - ./ecommerce-users-service/tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules

  # Product Service
  product-service:
    build:
      context: ./ecommerce-products-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:mongo123@mongodb:27017/productdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - microservices-network
    volumes:
      - ./ecommerce-products-service/src:/usr/src/app/src
      - ./ecommerce-products-service/package.json:/usr/src/app/package.json
      - ./ecommerce-products-service/tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules

  # Notification Service
  notification-service:
    build:
      context: ./ecommerce-notifications-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis123
    depends_on:
      - redis
    networks:
      - microservices-network
    volumes:
      - ./ecommerce-notifications-service/src:/usr/src/app/src
      - ./ecommerce-notifications-service/package.json:/usr/src/app/package.json
      - ./ecommerce-notifications-service/tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules

  # Shopping Cart Service
  shopping-cart-service:
    build:
      context: ./ecommerce-shopping-cart-service
      dockerfile: Dockerfile
    container_name: shopping-cart-service
    environment:
      - NODE_ENV=development
      - RABBITMQ_URLS=amqp://rabbitmq:rabbitmq123@microservices-rabbitmq:5672
      - RABBITMQ_QUEUE=shopping_cart_queue
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis123
    depends_on:
      - rabbitmq
      - redis
    networks:
      - microservices-network
    volumes:
      - ./ecommerce-shopping-cart-service/src:/usr/src/app/src
      - ./ecommerce-shopping-cart-service/package.json:/usr/src/app/package.json
      - ./ecommerce-shopping-cart-service/tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules

  # Orders Service
  orders-service:
    build:
      context: ./ecommerce-orders-service
      dockerfile: Dockerfile
    container_name: orders-service
    ports:
      - '3004:3004'
    environment:
      - NODE_ENV=development
      - PORT=3004
      - RABBITMQ_URLS=amqp://rabbitmq:rabbitmq123@microservices-rabbitmq:5672
      - RABBITMQ_QUEUE=orders_queue
      - DATABASE_URL=postgresql://postgres:postgres123@orders-postgres:5432/ordersdb?schema=public
    depends_on:
      - rabbitmq
      - orders-postgres
    networks:
      - microservices-network
    volumes:
      - ./ecommerce-orders-service/src:/usr/src/app/src
      - ./ecommerce-orders-service/package.json:/usr/src/app/package.json
      - ./ecommerce-orders-service/tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules

  # Payments Service
  payments-service:
    build:
      context: ./ecommerce-payments-service
      dockerfile: Dockerfile
    container_name: payments-service
    ports:
      - '3005:3005'
    environment:
      - NODE_ENV=development
      - PORT=3005
      - RABBITMQ_URLS=amqp://rabbitmq:rabbitmq123@microservices-rabbitmq:5672
      - RABBITMQ_QUEUE=payments_queue
      - STRIPE_SECRET_KEY=your_stripe_key
      - STRIPE_ENDPOINT_SECRET=your_stripe_endpoint_secret
      - PAYMENTS_CANCEL_URL=http://localhost:3000/cancel
      - PAYMENTS_SUCCESS_URL=http://localhost:3000/success
    depends_on:
      - rabbitmq
    networks:
      - microservices-network
    volumes:
      - ./ecommerce-payments-service/src:/usr/src/app/src
      - ./ecommerce-payments-service/package.json:/usr/src/app/package.json
      - ./ecommerce-payments-service/tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules

  # Base de datos específica para órdenes
  orders-postgres:
    image: postgres:15
    container_name: orders-postgres
    environment:
      - POSTGRES_DB=ordersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5433:5432'
    volumes:
      - orders_postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  orders_postgres_data:
    driver: local

networks:
  microservices-network:
    driver: bridge

